[package]
name = "terminal_roborio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roborio = { path = "../roborio" }
crossterm = "0.26"
unicode-width = "0.1"
bitflags = "*"